// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rezept.app;

import com.rezept.app.ComposedofPK;
import java.io.Serializable;

privileged aspect ComposedofPK_Roo_Serializable {
    
    declare parents: ComposedofPK implements Serializable;
    
    private static final long ComposedofPK.serialVersionUID = 1L;
    
}
