// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rezept.app;

import com.rezept.app.Country;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Country_Roo_Configurable {
    
    declare @type: Country: @Configurable;
    
}
