// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rezept.app;

import com.rezept.app.FriendPK;
import java.io.Serializable;

privileged aspect FriendPK_Roo_Serializable {
    
    declare parents: FriendPK implements Serializable;
    
    private static final long FriendPK.serialVersionUID = 1L;
    
}
